spring:
  profiles:
    active: development
logging:
  level:
    root: INFO
    org.springframework.*: INFO
---
server:
  port: 8080
  
---
spring:
  data:    mongodb:      port: 27017
      host: localhost
      database: ArchinautAnalisys
